### ISSUE TITLE
MAD Calculation Support

### ISSUE THREAD

**Issue by 7020391narita** [Soldelli/MAD#11]
Hi, Thanks for your great work.
I want to request a MAD calculation support for visual/linguistic features because I would like to use MAD with my own prepared video and audio guide for my research.
Looking forward to your reply.

**Comment by Soldelli** [comment]
Dear @7020391narita this is entirely possible. 
I require that you share with me: 
 - Code with a working example
 - Checkpoint(s) 
 - Environment
 - Data preprocessing (if any)
 
This information should be sent over email at mattia.soldan@kaust.edu.sa.

**Comment by 7020391narita** [comment]
Thanks for your reply.
Actually I have already sent an email but have not received a reply.
Could you please check your spam folder?
My email address is 
s7020391@s.akita-u.ac.jp

**Comment by 7020391narita** [comment]
Thanks for your reply.
Actually I have already sent an email but have not received a reply.
Could you please check your spam folder?
My email address is 
s7020391@s.akita-u.ac.jp
