### ISSUE TITLE
clip encoder details

### ISSUE THREAD

**Issue by FromA2Z** [Soldelli/MAD#13]
thank you for your work, it is very helpful to the open source community.
Regarding clips, do you use visual_projection layers when extracting image features as in the clip source code?
![1701873287001](https://github.com/Soldelli/MAD/assets/108920982/a9ce9d32-2057-471e-9fcc-832548c18c08)

**Comment by Soldelli** [comment]
Dear @FromA2Z  the function we used to encode our frames is the following: [link](https://github.com/openai/CLIP/blob/main/clip/model.py#L340). 
This follows the official OpenAI CLIP implementation.
