### ISSUE TITLE
Question on the ``movie`` key in annotation.

### ISSUE THREAD

**Issue by SCZwangxiao** [Soldelli/MAD#2]
Hi, the dataset is awosome, and I am surfing on it. I've found that the details of ``movie`` key differ in splits.
Although you've mentioned that ``movie`` key of annotation file is not the title in ``DataInspection.ipynb``, all ``movie`` keys in test & val set contain movie title, while all those in train set are only digital ids.
Is there any special benefits of the above difference ?
I just wondering whether there is my favorite movie in the training set.

**Comment by Soldelli** [comment]
Hi @SCZwangxiao,
The difference in the movie's key stems from the origin of the data. 

- Training set: we use the same identifies as in the audiovault website.
- Val/test sets: we reuse the LSMDC keys (which include part of the movie name). 

If you have any other questions please feel free to reach out.

**Comment by Soldelli** [comment]
Hi, glad to hear from you.
The difference in the movie key stems from the origin of the data. For the
training set we use the same identifier as in the audiovault website, while
for the val/test split the data originated from the LAMDC dataset so we
used the say keys (which include part of the movie name).
If you are interested in knowing which are the titles in the training set I
can send the list to you or the mapping between the ids and the IMDb ids.

If you have any other questions please let me know.

Best,
Mattia
