### ISSUE TITLE
Eval with VLG-Net

### ISSUE THREAD

**Issue by MonsisGit** [Soldelli/MAD#5]
Hi,
I was wondering how you keep evaluation consistent with VLG-Net using the MAD dataset. Are you randomly sampling windows around their corresponding moments, e.g. for Fig.4 (Performance trend across different windows lengths) or Table 3 (Short Video Setup) from your paper? It seems like in [mad.py](https://github.com/Soldelli/MAD/blob/main/baselines/VLG-Net/lib/data/datasets/mad.py) you are randomly sampling different windows every time for evaluation?

Cheers

**Comment by Soldelli** [comment]
Dear @MonsisGit , random sampling of windows is only applied in training. 
At inference time the data loser provides windows for the entire movie with a half window overlap. (Simple sliding window)

I suggest you use ipdb and verify this detail at inference time. 
No randomness is involved in the evaluation process. 

Let me know if I can assist you further.
