### ISSUE TITLE
Where can I download MAD-v2

### ISSUE THREAD

**Issue by huangjinghuangjing** [Soldelli/MAD#6]
Seeing that MAD-v2 is already available, where can I download it? And what is the difference between it and v1?

**Comment by Soldelli** [comment]
Dear @huangjinghuangjing, we will release the annotations as soon as the paper is available on ArXiv. Keep an eye out, it will happen soon.

**Comment by huangjinghuangjing** [comment]
Thanks for the reply, looking forward to your wonderful work.
