### ISSUE TITLE
About the using of ChatGPT

### ISSUE THREAD

**Issue by TousakaNagio** [Soldelli/MAD#7]
Hi, thank you for your great work, it helps me a lot on my research. I have signed the NDA and downloaded the dataset. My question is whether can I upload part of the annotations such as description to the ChatGPT to preprocesse the data? Is is allowed under the NDA? Thank you for your reply.

Best Regard

**Comment by Soldelli** [comment]
Dear @TousakaNagio, we are pleased to know that you've found our dataset useful for your research.

Regarding your inquiry. In alignment with the Non-Disclosure Agreement policy, you are granted the possibility to utilise ChatGPT for the purpose that best suits your requirements. 

However, it is essential that any new data, specifically any transformations of the provided annotations, be disseminated solely through our designated systems. This procedure ensures that future users gain access to the annotations only after adhering to our NDA, thereby maintaining the integrity of the data and the interests of all parties involved.

Should you have further questions or require additional assistance, please do not hesitate to get in touch with us at your convenience.

Best regards,
The MAD team
