### ISSUE TITLE
Dataset Download Issue

### ISSUE THREAD

**Issue by typ1012** [Soldelli/MAD#9]
Thanks for your great work. 

When I tried to open the download page, I encountered the following issue:

Not Found
The requested URL was not found on this server.
Apache/2.4.29 (Ubuntu) Server at exrcsdrive.kaust.edu.sa Port 443

**Comment by Soldelli** [comment]
Dear @typ1012 , a patch in the downloading script was created. Kindly pull the repository again and proceed to download.
